"""autogenerated by genpy from brio_vision/Is_This_EasierRequest.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Is_This_EasierRequest(genpy.Message):
  _md5sum = "e18bcc043f19988bdc758eef414a0414"
  _type = "brio_vision/Is_This_EasierRequest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """string response_status

"""
  __slots__ = ['response_status']
  _slot_types = ['string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       response_status

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Is_This_EasierRequest, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.response_status is None:
        self.response_status = ''
    else:
      self.response_status = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.response_status
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.response_status = str[start:end].decode('utf-8')
      else:
        self.response_status = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.response_status
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.response_status = str[start:end].decode('utf-8')
      else:
        self.response_status = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
"""autogenerated by genpy from brio_vision/Is_This_EasierResponse.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import brio_vision.msg

class Is_This_EasierResponse(genpy.Message):
  _md5sum = "88ac6264ea1183b6ecef60ddfa07bead"
  _type = "brio_vision/Is_This_EasierResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """brio_vision/Container get_message


================================================================================
MSG: brio_vision/Container
Data_Type[] date_container

================================================================================
MSG: brio_vision/Data_Type
int32 center_index
int32 head_conn_index
int32 back_conn_index
string piece_type

"""
  __slots__ = ['get_message']
  _slot_types = ['brio_vision/Container']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       get_message

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Is_This_EasierResponse, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.get_message is None:
        self.get_message = brio_vision.msg.Container()
    else:
      self.get_message = brio_vision.msg.Container()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.get_message.date_container)
      buff.write(_struct_I.pack(length))
      for val1 in self.get_message.date_container:
        _x = val1
        buff.write(_struct_3i.pack(_x.center_index, _x.head_conn_index, _x.back_conn_index))
        _x = val1.piece_type
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.get_message is None:
        self.get_message = brio_vision.msg.Container()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.get_message.date_container = []
      for i in range(0, length):
        val1 = brio_vision.msg.Data_Type()
        _x = val1
        start = end
        end += 12
        (_x.center_index, _x.head_conn_index, _x.back_conn_index,) = _struct_3i.unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.piece_type = str[start:end].decode('utf-8')
        else:
          val1.piece_type = str[start:end]
        self.get_message.date_container.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.get_message.date_container)
      buff.write(_struct_I.pack(length))
      for val1 in self.get_message.date_container:
        _x = val1
        buff.write(_struct_3i.pack(_x.center_index, _x.head_conn_index, _x.back_conn_index))
        _x = val1.piece_type
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.get_message is None:
        self.get_message = brio_vision.msg.Container()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.get_message.date_container = []
      for i in range(0, length):
        val1 = brio_vision.msg.Data_Type()
        _x = val1
        start = end
        end += 12
        (_x.center_index, _x.head_conn_index, _x.back_conn_index,) = _struct_3i.unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.piece_type = str[start:end].decode('utf-8')
        else:
          val1.piece_type = str[start:end]
        self.get_message.date_container.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3i = struct.Struct("<3i")
class Is_This_Easier(object):
  _type          = 'brio_vision/Is_This_Easier'
  _md5sum = 'b793477c3837845ccb4fa4623a02615d'
  _request_class  = Is_This_EasierRequest
  _response_class = Is_This_EasierResponse
