/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/paul/ros_ws/src/brio_vision/srv/Is_This_Easier.srv
 *
 */


#ifndef BRIO_VISION_MESSAGE_IS_THIS_EASIERRESPONSE_H
#define BRIO_VISION_MESSAGE_IS_THIS_EASIERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <brio_vision/Container.h>

namespace brio_vision
{
template <class ContainerAllocator>
struct Is_This_EasierResponse_
{
  typedef Is_This_EasierResponse_<ContainerAllocator> Type;

  Is_This_EasierResponse_()
    : get_message()  {
    }
  Is_This_EasierResponse_(const ContainerAllocator& _alloc)
    : get_message(_alloc)  {
    }



   typedef  ::brio_vision::Container_<ContainerAllocator>  _get_message_type;
  _get_message_type get_message;




  typedef boost::shared_ptr< ::brio_vision::Is_This_EasierResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::brio_vision::Is_This_EasierResponse_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct Is_This_EasierResponse_

typedef ::brio_vision::Is_This_EasierResponse_<std::allocator<void> > Is_This_EasierResponse;

typedef boost::shared_ptr< ::brio_vision::Is_This_EasierResponse > Is_This_EasierResponsePtr;
typedef boost::shared_ptr< ::brio_vision::Is_This_EasierResponse const> Is_This_EasierResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::brio_vision::Is_This_EasierResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::brio_vision::Is_This_EasierResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace brio_vision

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'brio_vision': ['/home/paul/ros_ws/src/brio_vision/msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::brio_vision::Is_This_EasierResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::brio_vision::Is_This_EasierResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::brio_vision::Is_This_EasierResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::brio_vision::Is_This_EasierResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::brio_vision::Is_This_EasierResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::brio_vision::Is_This_EasierResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::brio_vision::Is_This_EasierResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "88ac6264ea1183b6ecef60ddfa07bead";
  }

  static const char* value(const ::brio_vision::Is_This_EasierResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x88ac6264ea1183b6ULL;
  static const uint64_t static_value2 = 0xecef60ddfa07beadULL;
};

template<class ContainerAllocator>
struct DataType< ::brio_vision::Is_This_EasierResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "brio_vision/Is_This_EasierResponse";
  }

  static const char* value(const ::brio_vision::Is_This_EasierResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::brio_vision::Is_This_EasierResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "brio_vision/Container get_message\n\
\n\
\n\
================================================================================\n\
MSG: brio_vision/Container\n\
Data_Type[] date_container\n\
\n\
================================================================================\n\
MSG: brio_vision/Data_Type\n\
int32 center_index\n\
int32 head_conn_index\n\
int32 back_conn_index\n\
string piece_type\n\
";
  }

  static const char* value(const ::brio_vision::Is_This_EasierResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::brio_vision::Is_This_EasierResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.get_message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Is_This_EasierResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::brio_vision::Is_This_EasierResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::brio_vision::Is_This_EasierResponse_<ContainerAllocator>& v)
  {
    s << indent << "get_message: ";
    s << std::endl;
    Printer< ::brio_vision::Container_<ContainerAllocator> >::stream(s, indent + "  ", v.get_message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BRIO_VISION_MESSAGE_IS_THIS_EASIERRESPONSE_H
