/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/paul/ros_ws/src/brio_vision/srv/Is_This_Easier.srv
 *
 */


#ifndef BRIO_VISION_MESSAGE_IS_THIS_EASIER_H
#define BRIO_VISION_MESSAGE_IS_THIS_EASIER_H

#include <ros/service_traits.h>


#include <brio_vision/Is_This_EasierRequest.h>
#include <brio_vision/Is_This_EasierResponse.h>


namespace brio_vision
{

struct Is_This_Easier
{

typedef Is_This_EasierRequest Request;
typedef Is_This_EasierResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Is_This_Easier
} // namespace brio_vision


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::brio_vision::Is_This_Easier > {
  static const char* value()
  {
    return "b793477c3837845ccb4fa4623a02615d";
  }

  static const char* value(const ::brio_vision::Is_This_Easier&) { return value(); }
};

template<>
struct DataType< ::brio_vision::Is_This_Easier > {
  static const char* value()
  {
    return "brio_vision/Is_This_Easier";
  }

  static const char* value(const ::brio_vision::Is_This_Easier&) { return value(); }
};


// service_traits::MD5Sum< ::brio_vision::Is_This_EasierRequest> should match 
// service_traits::MD5Sum< ::brio_vision::Is_This_Easier > 
template<>
struct MD5Sum< ::brio_vision::Is_This_EasierRequest>
{
  static const char* value()
  {
    return MD5Sum< ::brio_vision::Is_This_Easier >::value();
  }
  static const char* value(const ::brio_vision::Is_This_EasierRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::brio_vision::Is_This_EasierRequest> should match 
// service_traits::DataType< ::brio_vision::Is_This_Easier > 
template<>
struct DataType< ::brio_vision::Is_This_EasierRequest>
{
  static const char* value()
  {
    return DataType< ::brio_vision::Is_This_Easier >::value();
  }
  static const char* value(const ::brio_vision::Is_This_EasierRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::brio_vision::Is_This_EasierResponse> should match 
// service_traits::MD5Sum< ::brio_vision::Is_This_Easier > 
template<>
struct MD5Sum< ::brio_vision::Is_This_EasierResponse>
{
  static const char* value()
  {
    return MD5Sum< ::brio_vision::Is_This_Easier >::value();
  }
  static const char* value(const ::brio_vision::Is_This_EasierResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::brio_vision::Is_This_EasierResponse> should match 
// service_traits::DataType< ::brio_vision::Is_This_Easier > 
template<>
struct DataType< ::brio_vision::Is_This_EasierResponse>
{
  static const char* value()
  {
    return DataType< ::brio_vision::Is_This_Easier >::value();
  }
  static const char* value(const ::brio_vision::Is_This_EasierResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BRIO_VISION_MESSAGE_IS_THIS_EASIER_H
